services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped


  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules  # ← важно, иначе node_modules перезапишется
  #   environment:
  #     - VITE_API_URL=https://russiantrainer.onrender.com  # ← URL бэкенда
  #   depends_on:
  #     - api
  #   restart: unless-stopped